spring.application.name=restservices

# Active profile comes from env
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Shared JPA settings
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
# hibernate should only validate, liquibase does the creating/editing

coingecko.api.key=${COINGECKO_API}
coingecko.api.url=${COINGECKO_URL}
coingecko.api.defaultCurrency=usd
cors.config.url=${CORS_CONFIG_URL}
cors.config.port=${CORS_CONFIG_PORT}

application.cache.hazelcast.mode = server
application.cache.hazelcast.cluster-name = dev
application.cache.hazelcast.instance-name = dev-node-1
application.cache.hazelcast.server.primary-address = 127.0.0.1
application.cache.hazelcast.server.port = 5701
logging.level.org.springframework.cache=INFO
