spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.contexts=prod

spring.jpa.show-sql=false

# Production hardening
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never