spring.application.name=restservices

# Active profile comes from env
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Shared JPA settings
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

coingecko.api.key=${COINGECKO_API}
coingecko.api.url=${COINGECKO_URL}
cors.config.url=${CORS_CONFIG_URL}
cors.config.port=${CORS_CONFIG_PORT}