spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
# hibernate should only validate, liquibase does the creating/editing
spring.jpa.show-sql=false
logging.level.root=WARN
spring.liquibase.contexts=test
spring.cache.type=none

